# all blocks follow the following format
# [type of block]
#     option1 = value
#     option2 = vale

[[conf]]
    [conf.static.options]
        instance = "1"
        text = "hello, world"

[[conf]]
    [conf.static.options]
        instance = "2"
        text = "bbbbbbbb"

[[conf]]
    [conf.time.options]
        # TimeFormat = "2006-01-02 15:04:05"
        # TimeZone = "Local"
        # Format = "{{.Timezone}}: {{.Time}}"
