# all blocks follow the following format
# [type of block]
#     option1 = value
#     option2 = vale

[[conf]]
    [conf.static]
        instance = "1"
        text = "hello, world"

[[conf]]
    [conf.static]
        instance = "2"
        text = "bbbbbbbb"

[[conf]]
    [conf.time]
        format = "2006"
